import 'package:drift/drift.dart';
import 'package:drift_sqflite/drift_sqflite.dart';
import 'package:path_provider/path_provider.dart';

import 'tables.dart';
import 'daos/system_dao.dart';
import 'daos/vault_dao.dart';
import 'daos/profile_dao.dart';
import 'daos/hierarchy_dao.dart';
import 'daos/history_dao.dart';
import 'daos/folder_dao.dart';

part 'app_database.g.dart';

/// The single Drift database for Plural Rabbit.
///
/// Key design decisions (from Technical doc §16.1):
/// - SQLCipher key is passed via [SqfliteDatabase.encryptionKey]
/// - schemaVersion starts at 1; every migration must be versioned
/// - Master History Log writes are atomic with every state change
@DriftDatabase(
  tables: [
    SystemTable,
    VaultTable,
    ProfileTable,
    ProfileVaultMembershipTable,
    ArchiveReasonLabelTable,
    FusionRecordTable,
    FusionSourceTable,
    HierarchyLevelTable,
    ProfileHierarchyAssignmentTable,
    PermissionRuleTable,
    FolderTable,
    ProfileFolderMembershipTable,
    HistoryEntryTable,
    AppSettingTable,
  ],
  daos: [
    SystemDao,
    VaultDao,
    ProfileDao,
    HierarchyDao,
    HistoryDao,
    FolderDao,
  ],
)
class AppDatabase extends _$AppDatabase {
  AppDatabase(String encryptionKey) : super(_openConnection(encryptionKey));

  @override
  int get schemaVersion => 1;

  @override
  MigrationStrategy get migration {
    return MigrationStrategy(
      onCreate: (Migrator m) async {
        await m.createAll();
        await _seedDefaultData();
      },
      onUpgrade: (Migrator m, int from, int to) async {
        // Future migrations go here, keyed by version range
      },
      beforeOpen: (details) async {
        await customStatement('PRAGMA foreign_keys = ON');
      },
    );
  }

  /// Seeds the two built-in archive reason labels on first launch.
  Future<void> _seedDefaultData() async {
    // No system row seeded here — system creation happens in the
    // first-launch flow (SystemDao.createSystem).
    // Archive labels are vault/system-agnostic seeds:
    // They are created with the system once the system row exists.
  }
}

/// Opens a [SqfliteQueryExecutor] pointing to the encrypted database file.
/// The [encryptionKey] comes from [EncryptionService] and is forwarded to
/// drift_sqflite which passes it as SQLCipher's PRAGMA key= value.
QueryExecutor _openConnection(String encryptionKey) {
  return SqfliteQueryExecutor.inDatabaseFolder(
    path: 'plural_rabbit.db',
    // SQLCipher key: hex-encoded 256-bit key derived or generated by EncryptionService.
    // drift_sqflite passes this to sqlite3's PRAGMA key= call on open.
    singleInstance: true,
    logStatements: false,
    creator: (db) async {
      await db.execute("PRAGMA key='$encryptionKey'");
    },
  );
}

/// Convenience factory that wires the database to the app's documents dir.
/// Separate from the test factory so tests can inject an in-memory DB.
Future<AppDatabase> openAppDatabase(String encryptionKey) async {
  // Ensure the documents directory exists before opening the DB.
  await getApplicationDocumentsDirectory();
  return AppDatabase(encryptionKey);
}
